# Generated by Django 4.2.7 on 2025-10-28 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import whiteboard.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Session name/title', max_length=200)),
                ('code', models.CharField(default=whiteboard.models.generate_session_code, help_text='Unique join code for students', max_length=6, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the session is currently active')),
                ('snapshot', models.ImageField(blank=True, help_text='Saved snapshot of the whiteboard', null=True, upload_to='session_snapshots/')),
                ('creator', models.ForeignKey(help_text='Teacher who created this session', on_delete=django.db.models.deletion.CASCADE, related_name='created_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Whiteboard Session',
                'verbose_name_plural': 'Whiteboard Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Stroke',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool', models.CharField(choices=[('pen', 'Pen'), ('eraser', 'Eraser'), ('rectangle', 'Rectangle'), ('circle', 'Circle'), ('arrow', 'Arrow'), ('text', 'Text')], max_length=20)),
                ('data', models.JSONField(help_text="Stroke data: {points: [[x,y]...], color: '#000', width: 2, text: 'abc'}")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.IntegerField(default=0, help_text='Order of stroke for replay (auto-incremented)')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strokes', to='whiteboard.session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strokes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stroke',
                'verbose_name_plural': 'Strokes',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_online', models.BooleanField(default=True)),
                ('hand_raised', models.BooleanField(default=False, help_text='Student has raised hand for teacher attention')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='whiteboard.session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joined_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['joined_at'],
                'unique_together': {('session', 'user')},
            },
        ),
    ]
